server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/school
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

  properties :
    hibenate :
      format_sql : true
    database : postgres
    database-platform: org.hibernate.dialect.PostgreSQLDialect


